fix: do not clone File for compression command
Cloning the file object for the compression command will cause the
`test_examine_compressed_cpio` test to fail in around 10% of the CI
runs:

```
thread 'test_examine_compressed_cpio' panicked at tests/cli.rs:65:9:
assertion `left == right` failed
  left: "lzop: Inappropriate ioctl for device: <stdin>\n"
 right: ""
```